version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "npm"
    directory: "web/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
