name: macOS Release
permissions:
  contents: write

on:
  push:
    tags:
      - "*"
      - "!*-alpha*"
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          npm install
          REACT_APP_VERSION=$(git describe --tags) npm run build
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Build Backend
        run: |
          go mod download
          go build -ldflags "-X 'happy-api/common.Version=$(git describe --tags)'" -o happy-api-macos