name: Windows Release
permissions:
  contents: write

on:
  push:
    tags:
      - "*"
      - "!*-alpha*"
jobs:
  release:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Build Frontend
        env:
          CI: ""
        run: |
          cd web
          npm install
          REACT_APP_VERSION=$(git describe --tags) npm run build
          cd ..
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: Build Backend
        run: |
          go mod download
          go build -ldflags "-s -w -X 'happy-api/common.Version=$(git describe --tags)'" -o happy-api.exe

      - name: automatic releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-latest"
          prerelease: false
          title: "Happy API Windows 自动构建最新版本"
          files: |
            happy-api.exe